language: python
env:
  global:
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TGZ=helm-v2.14.0-linux-amd64.tar.gz
    - YAMLLINT_VERSION=1.15.0
install:
  # Install Helm
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only
  # Install YamlLint
  - sudo pip install yamllint=="${YAMLLINT_VERSION}"
  # Install Go
  - wget -c https://storage.googleapis.com/golang/go1.7.3.linux-amd64.tar.gz
  - sudo tar -C /usr/local -xvzf go1.7.3.linux-amd64.tar.gz
  - export  PATH=$PATH:/usr/local/go/bin
script:
  - yamllint -c .yamllint.yml -s $(find . -type f -name "Chart.yaml")
  - yamllint -c .yamllint.yml -s $(find . -type f -name "values.yaml")
  # Now load the helm dependencies
  - make dependencies
  # Run Helm lint
  - helm lint ./charts/pega  
  - helm lint ./charts/addons
  # Run GO helm unit tests
  - mkdir $TRAVIS_BUILD_DIR/terratest/bin
  - export GOPATH=$TRAVIS_BUILD_DIR/terratest
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/terratest/bin
  - cd terratest/src/test
  - dep ensure
  - go test deploy_test.go common_utility.go standard_deployment_utility.go
  - go test install_test.go common_utility.go
  - go test install_deploy_test.go common_utility.go standard_deployment_utility.go
  - cd $TRAVIS_BUILD_DIR
  - chmod 777 before_deploy.sh
before_deploy:
  #- ./before_deploy.sh
  - make packages
  - make examples
deploy:
  - provider: releases
    api_key:
      secure: BYtlhzzsWk85KrZejivAVO6W6bDWX85Ixv7aIPd4dFu0QPJA2vINqPGCOrOmSDDjrL3kIaosPfZzrtn/kqKJ3j/l7NrrQyfzGs09wuRS2sU1eycWS/PUD9+XrWen76Px9fFVMxgkf9Gp+C6N24BYwAesh05vjS7rYHad4Zkc9uSYO4AIQ1fmkDRsn2NhXrk6HMFaJkPyFiIqtYRbW852apRq8uj2y/S9xGSIjIpa1H9t5cYgDb1dKKxXY/Z8XvFrC+OwDz7E98tvM0jUbgr5FwHvXmbgieRBroMb3XIhlRt+8z0/EHX195pe9lyax5kH+xJe/JiTk+E2w6UIOpkBh8KQVo6G5/AV56DNrTR5jbm8nWAGOmraT9daD+1rO1X7Ub0aHogqt4nWnZYTrsa0fnGJ/wGev3uBCZrKnl7h6qP6PstwbJh8BxuVqbLvydkO5bkTiwWDwsuwWZYe4WvQkzXn2oAKg/0FruYPQDPV6g5plhc6IOnomsuZvJFR9OFoN0hKeofWCAEze/mPshD2t4j4VHZKXGtUpHhWDZgbVDf2wnDLdqyTu/fqh3wId5EXekVd3k2tcYT4MhpeiBEq47tHB0aFZt0poo4xvkcQhgKhUt+RheHgyaLy68iHXAGGBXUi9Ok6ongAIhjcTZYJaDgbDmrCYqY4f9r+1p30XTY=
    file:
      - pega-kubernetes-example.tar.gz
      - pega-openshift-example.tar.gz
      - pega-azure-aks-example.tar.gz
      - pega-aws-eks-example.tar.gz
      - pega-google-gke-example.tar.gz
      - pega-pivotal-pks-example.tar.gz
    skip_cleanup: true
    on:
      repo: scrumteamwhitewalkers/pega-helm-charts-1
      tags: true
  - provider: bintray
    file: descriptor.json
    user: kishorv
    key:
      secure: jRzfiG7pzgbCh+aGEvpskD+7cCs9fgiqtfUAdTMqG85qEi3n4KcqeB8+3eUGj3aNK5KQE86zUD6kCC4fQDXt+vH9BJWPQ/ltwHvlzW5TLG/rXeg8LOcBa8neOo+mlMoq5yzJUUFlWdaWmtj0/2pQtPIazb9gWGAZHCoEcgU8z0AI47k0GVfUSxXVobil2TgDWzL0IHf+L5yLWVsHi/70EuOkbKuNEDRhCAg9P18INGqdW8krTpb9cxIO1440dSBxC1UQVQcj+cpDzRq9dHgu/yVr/y00gIASQBo4mWNIXvpBEy/ytpUeJI5/28h/60jvKDjcOPHACS7GIALl4ufL9Nf7g2vLJxayKzEiTygbJEhQSmzpNwsVrzGOVsluOMoyZ9+pTArzuBW75WJj2vx0YMLHopSnS3TljC6lFGAgP9AvIFJUnhBOPMWfqXy18WpW2kyQqbyvB228s7zQ42iftA7+E7wLxCJZ/RqxCuWvy8K2u5OjqoAbslxttCXzUTuGtnUaV7dIgN6eIkQp+Ae2Q1htrRFFEmYoCg2GKGS2LuTdkAC52r9zM+hEsX1WZVBitPqVmzjTnXjPu8Jckexxf1IQ953mqOAV3nMicCkneT5QvWmSEVUlakX70euIO1vPmk1Ni/XBHlEe7AuwnQ4UehTjIQcuKmx/XIfFeJKoVJU=
    skip_cleanup: true
    on:
      all_branches: true
      tags: true 