language: python
env:
  global:
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TGZ=helm-v2.11.0-linux-amd64.tar.gz
    - YAMLLINT_VERSION=1.15.0
install:
  # Install Helm
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only
script:
  - curl -o index.yaml https://stwhitewalkers.bintray.com/pega-helm-charts/index.yaml
  - helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
  - helm dep update ./charts/pega/
  - helm package ./charts/pega/
  - helm repo index --merge index.yaml --url https://dl.bintray.com/pegasystems/pega-helm-charts/ .
deploy:
  provider: bintray
  file: descriptor.json
  user: scrumteamwhitewalkers
  key:
    secure: SC1mdfvKoEQC8JT+sHbQ3DhUbGdTKvDZ/lGFEStrupCpKyAnnmMI13pMsVmf7gwDclpWvbrsP/mn0IJficXKQ+BVPJV7/BSnRux77JDR+xBiVR/p/DTegvo5qSajl3HdcfgH+Lr+jdgsexU47GZrdS6mYUTSEl4kOCkFigcnbdDGspkj5RNcOhRysLEB4qyYoeUsKE45mSv+Ai6lBXqzbucfbH2fkYxYtyoJ5UHmMRT/EG4dCNRgg0Ew3tDBvNHUp5JGtZOLu01pIpuzCAxrX8koWMary29xbFmLu3r96QLXzZauqv1kdbFk0GQuVa6a5iYVsvGd3ohRz5sTgbdChVI0PX3IfKQoFA8mUeWFsrfneo2r6l3cBNQ6OTcLzKRRGGSuI9TehePodaiKtdGE1MyMPo+Uv6rcgxr/7h2GjzAdZX2d0KRdhuvafTCO8ySePpO3sh+OCcbZ/gVT9hGCk4cgx3kztyIYnsm1HtxLLEG+uUT6hLqNgLZ2eE6Gn7+cO6DllnflGpj1M1CKVmlcZLRNUxEVf3gDXPEJ2vJOh27cqfyaOU+mETBcQ1MQqOZMNS3Tn1foZdgZX5d70jpj5P0RP5w1O0/iPWU+U6hoTb4VlEhm/uTGdfvQZaZ0OgkA+/JR34HO2WKk7csTkI6s/Zi6R5Ud58SIhO0oZsYUX24=
  skip_cleanup: true
branches:
  only:
    - /^release/