language: python
env:
  global:
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TGZ=helm-v2.14.0-linux-amd64.tar.gz
    - YAMLLINT_VERSION=1.15.0
install:
  # Install Helm
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only
  # Install YamlLint
  - sudo pip install yamllint=="${YAMLLINT_VERSION}"
  # Install Go
  - wget -c https://storage.googleapis.com/golang/go1.7.3.linux-amd64.tar.gz
  - sudo tar -C /usr/local -xvzf go1.7.3.linux-amd64.tar.gz
  - export  PATH=$PATH:/usr/local/go/bin
script:
  - yamllint -c .yamllint.yml -s $(find . -type f -name "Chart.yaml")
  - yamllint -c .yamllint.yml -s $(find . -type f -name "values.yaml")
  # Now load the helm dependencies
  - make dependencies
  # Run Helm lint
  - helm lint ./charts/pega  
  - helm lint ./charts/addons
  # Run GO helm unit tests
  - mkdir $TRAVIS_BUILD_DIR/terratest/bin
  - export GOPATH=$TRAVIS_BUILD_DIR/terratest
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/terratest/bin
  - cd terratest/src/test
  - dep ensure
  - go test deploy_test.go common_utility.go deployment_utility.go
  - go test install_test.go common_utility.go installer_utility.go
  - go test install_deploy_test.go common_utility.go deployment_utility.go installer_utility.go
  - go test upgrade_test.go common_utility.go installer_utility.go
  - go test upgrade_deploy_test.go common_utility.go deployment_utility.go installer_utility.go
  - go test aks_deploy_test.go common_utility.go deployment_utility.go installer_utility.go
  - go test eks_deploy_test.go common_utility.go deployment_utility.go
  - go test openshift_test.go common_utility.go deployment_utility.go
  - go test invalidAction_test.go
  - cd $TRAVIS_BUILD_DIR
  - chmod 777 before_deploy.sh
before_deploy:
  - ./before_deploy.sh  
  - make examples
deploy:
  - provider: releases
    api_key:
      secure: P1fC0GErp+o5fgyofb3kxuJUjJG3zQm9a34N2CJS5Z3+JeC8vB0WAYCRKoCePZp5qE0fAF2gjgjiYswhnnJm3z9gOC/wdyWpxGaYd0iRJyeLOegeQg4s6j8Gj2cxdpdQiKBwr3+MRco7GGrDiETTO6229q6UQunN7T1wmAR7uRIYXL6iHSD/p7uZsyGN3RRilryog4K5mkP3+qegzTGTxFBBXq8RyxFXY6pgeRAP+6Pxi9pGbT7i+lB9hjeJ1Tw20LFNfoJF9DNVEblS/Mu5xM95m9IFXXJsHA3Sc/AU6YltjirjqHq48jnYfwyL1S2Tuqwigdj1pTmtdttT874i/1wSZai9JhilDgNGN/+XNPe4J6dpKndNJDDzIbEJW5LFRqcaYKWUPoX0pI+Aykh6g91Jyd8GPNUukEX1gnbfJJ2QCqPiPspiULkwBIJ569/AKkfrWbeJ73xhRdOL3tjG7DDJU78q5/1OzPcbT3/v5YGsfRKW85NsYyOBh2kKerGt2Sipww+kIiDzLqJY+DWEj31p6VCflYqUGO/GGGKOjEi3Wtg6T59mlFxjglDjvLzVUJwcKvK1+ZrIQpKV3Re3qoBhN19mXM13DDtSMWi7iuferYXsssuoETDS5fRoYAdcLiOrmmNfBDbf0GlolQf9N/7xcF+XV9uMtErV0Cqjx/c=
    file:
      - pega-kubernetes-example.tar.gz
      - pega-openshift-example.tar.gz
      - pega-azure-aks-example.tar.gz
      - pega-aws-eks-example.tar.gz
      - pega-google-gke-example.tar.gz
      - pega-pivotal-pks-example.tar.gz
    skip_cleanup: true
    on:
      repo: scrumteamwhitewalkers/pega-helm-charts-1
      tags: true
  - provider: bintray
    file: descriptor.json
    user: kishorv
    key:
      secure: ux+xzwMHu1B3ORU+wXBMPahZf6/WRYDSN4cCkpPMAiW9Sems8QbYJJOJ5HftCOcIy7IahTC5rCAe3fXw0vWFV3vfq6SudVcKcJfbu0EZMvnjETAGShkl9d1/HuxC56lKILH25hoIPu58w5AaGD3zxgBMDlgdwgX84z+wVIxfS99UzdApGeVOy3Tz8h4FZPo3kpjvl8+YVl+masan8su8zxcxHb6arT3HSPnKGUqVzY4dlWUckKlcYmVe/S8yJ0djM3Sg+m7Hcn9cYYm2tNcDzPZpaCnHM7Yf4UHOZc+NBiJ6520iZJatMT7Zgp0o5N0Tz6EGbChzqMSz1DCpZ5H26GZB7IvW7dsrwZnd3PPn2YzKpuhzH3isFTvU62Q/Spp5KsQktCPZYrkVonh7AVJCiz2t+AaPwzSOpdW+B3Ff0lhZfDCMZm26cO+cw+bcEN9yLS8T6AeJjUrgjn/6mhGxAb/PdulpVN0i9EHKGesfm9f2rqjgBN/G1pTCIVy4JfKn3sNRkb1yzw0RySRW866Nd77cV3BXLNW5FHtskNk6S0o+Nk4lthBbiFB5+y1W8zyxgDpufpfsaX8onjG4z+OYl6YRxf6SAjefsbd1889UOL4Qay6aZPBqLaMpbjRPRSSxq+5ds2TvUjkbVdUNO+8Ec5XZZVgphQdO+qi/HVaNXIg=
    skip_cleanup: true
    on:
      all_branches: true
      tags: true 